### ISSUE TITLE
A way to send Ctrl+C and other control characters

### ISSUE THREAD

**Issue by carlosperate** [SpacehuhnTech/serialterminal#1]
Specially for this like MicroPython and CircuitPython serial, where Ctrl+C is used to enter the REPL.

Btw, great web serial terminal, I love it!

**Comment by spacehuhn** [comment]
Hi, thanks!
Recently started a circuit python project and thought the same. Will definitely add it as soon as I can take some time for it :)

**Comment by spacehuhn** [comment]
Ok found some time :D
Added support for CTRL+C and CTRL+D now. You can also turn it on/off in the settings. But it only works when you're in the text input field. Otherwise, the key combo is not detected.

**Comment by carlosperate** [comment]
Awesome, thanks!

I'm not too sure how to trigger it though. I can see the setting, so the update has been deployed and I must be loading it, but if I press the keys "ctrl"+"c" in the input field nothing happens? Even after clicking "send"?

**Comment by carlosperate** [comment]
Ahh, works in Chrome but not in Edge (macOS 12.1 x64, Edge v103.0.1264.5).

**Comment by carlosperate** [comment]
Nevermind, after closing and reopening Edge it started working 🤷‍♂️
Thanks again, awesome to have this feature!
